config/routes.rb
require 'sidekiq/web'

TmCard::Application.routes.draw do

  resources :resource_musics

  namespace :app do
    get "site/new"
    post "site/create"
    get "site/ajax_get_member"
    get "site/preview"
  end
  
  get '/home/dialog_banner'
  get '/home/dialog_music'
  resources :site_images do 
    collection {post :sort}
    collection {get :app}
    collection {get :meitu_load}
    collection {post :meitu_upload}
  end

  resources :members do
    collection {get :new_token}
    collection {post :verify_token}
  end

  resources :site_comments #for show on client
  resources :site_pages

  resources :sites do 
    resources :site_steps
    resources :site_comments #for admin manage
    collection do
      post :send_sms
    end
    get 'preview'
    get 'themes'
    get 'payment'
    post 'set_theme'
    post 'verify_payment_token'
    post :alipay_notify
  end
  namespace :sites do
    post "temp_form_update"
  end
  
  match '/s-:site_id(/p-:id)', to: "s#index", via: :get
  match '/templates(/page/:page)', to: "home#templates", via: :get, as: 'templates'
  match '/templates(/page/:page)', to: "home#templates", via: :get, as: 'ts'
  match '/templates/:id', to: "home#template", via: :get, as: 'template'
  match '/search(/page/:page)', to: "home#search", via: :get, as: 'search'
  match '/case(/page/:page)', to: "home#case", via: :get, as: 'case'
  match '/top(/:q)(/page/:page)', to: "home#top", via: :get, as: 'top'
  match '/biz(/page/:page)', to: "home#biz", via: :get, as: 'biz'
  match '/blog(/page/:page)', to: "home#blog", via: :get, as: 'blog'
  match '/post/:id', to: "home#post", via: :get, as: 'post'
  match '/pricing', to: "home#pricing", via: :get, as: 'pricing'
  match '/vip', to: "home#vip", via: :get, as: 'vip'
  match '/video', to: "home#video", via: :get, as: 'video'
  match '/zhuanpan_json/:id/:key', to: "home#zhuanpan_json", via: :get, as: 'zhuanpan_json'
  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: "omniauth_callbacks"}
  resources :users
  authenticate :user, lambda { |u| u.has_role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/site_comment.rb
class SiteComment < ActiveRecord::Base
  belongs_to :site
  belongs_to :template_page, class_name: 'Templates::Page'
  before_save :filter_hacker
  after_save :expire_cache

  private
    def filter_hacker
      content = nil if content =~ /(asdf|aaa|http|www|href|link|script|select|if|delay|sleep|wait|img|src|dir|file|prompt|alert|onmouseover|onclick)/i
    end

    #cache
    def expire_cache
      site = self.site
      return if site.nil?
      cache_paths = []
      cache_paths << File.join(Rails.root, 'public', 'page_cache', 's-' + site.short_title + '.html')
      site.site_pages.each do |site_page|
        cache_paths << File.join(Rails.root, 'public', 'page_cache', "s-#{site.short_title}", "p-#{site_page.short_title}.html")
      end
      cache_paths.each do |path|
        if File.exist?(path)
          FileUtils.rm_rf path
        end
      end
    end
end

app/controllers/site_comments_controller.rb
class SiteCommentsController < ApplicationController
  before_filter :authenticate_auth, only: [:destroy]
  before_action :set_site_comment, only: [:show, :edit, :update, :destroy]
  #skip CSRF on create.
  skip_before_filter :verify_authenticity_token

  layout false, only: [:new, :create]

  # GET /site_comments
  # GET /site_comments.json
  def index
    @site = Site.find_by(id: params[:site_id])
    redirect_to sites_url and return if @site.nil?
    authorize!(@site)

    @site_comments = @site.site_comments.order("updated_at DESC").page(params[:page])
  end

  # GET /site_comments/1
  # GET /site_comments/1.json
  def show
  end

  # GET /site_comments/new
  def new
    @site_comment = SiteComment.new
  end

  # GET /site_comments/1/edit
  def edit
  end

  # POST /site_comments
  # POST /site_comments.json
  def create
    if mobile_device?
      unless check_token
        render text: '不能重复提交' and return
      end
    end

    @site_comment = SiteComment.new(site_comment_params)

    respond_to do |format|
      if @site_comment.save
        #send notice to admin
        if Rails.env == 'production' && @site_comment.site_id == 1 && filter_backlist(@site_comment)
          SmsSendWorker.perform_async(ENV['ADMIN_PHONE'].split('|').join(','), "【维斗喜帖】#{@site_comment.mobile_phone}给你留言了：#{@site_comment.content}")
          SmsSendWorker.perform_async(@site_comment.mobile_phone, "【维斗喜帖】感谢你的留言！直接登录维斗喜帖即可制作，免费试用，获取帮助请加微信：18080810818")
        end

        format.html { render text: 'success' }
        format.json { render action: 'show', status: :created, location: @site_comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @site_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_comments/1
  # PATCH/PUT /site_comments/1.json
  def update
    authorize!(@site_comment.site)
    respond_to do |format|
      if @site_comment.update(site_comment_params)
        format.html { redirect_to @site_comment, notice: 'Site comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_comments/1
  # DELETE /site_comments/1.json
  def destroy
    authorize!(@site_comment.site)
    @site_comment.destroy
    respond_to do |format|
      format.html { redirect_to site_comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_comment
      @site_comment = SiteComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_comment_params
      params.require(:site_comment).permit(:site_id, :template_page_id, :name, :mobile_phone, :tel_phone, :email, :qq, :weixin, :gender, :birth, :address, :hobby, :content, :content2, :content3, :status, :updated_by, :note)
    end

    def filter_backlist(site_comment)
      return false if site_comment.name.blank? || site_comment.mobile_phone.blank? || site_comment.content.blank?
      return false if site_comment.mobile_phone !~ /^1\d{10}$/
      return false if site_comment.content =~ /(http:|www)/i
      return true
    end
end

app/helpers/site_comments_helper.rb
module SiteCommentsHelper
end

app/views/site_comments/_form.html.erb
<%= simple_form_for(@site_comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :site %>
    <%= f.association :template_page %>
    <%= f.input :name %>
    <%= f.input :mobile_phone %>
    <%= f.input :tel_phone %>
    <%= f.input :email %>
    <%= f.input :qq %>
    <%= f.input :weixin %>
    <%= f.input :gender %>
    <%= f.input :birth %>
    <%= f.input :address %>
    <%= f.input :hobby %>
    <%= f.input :content %>
    <%= f.input :content2 %>
    <%= f.input :content3 %>
    <%= f.input :status %>
    <%= f.input :updated_by %>
    <%= f.input :note %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/site_comments/_theme_one.html.erb
wefew
<%= render 'form' %>

app/views/site_comments/edit.html.erb
<h1>Editing site_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @site_comment %> |
<%= link_to 'Back', site_comments_path %>

app/views/site_comments/index.html.erb
<h1>留言列表</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>姓名</th>
      <th width="100px">电话</th>
      <th>留言</th>
      <th>其它</th>
      <th width="100px">添加时间</th>
      <th colspan="2">操作</th>
    </tr>
  </thead>
  <tbody>
    <% @site_comments.each do |site_comment| %>
      <tr>
        <td><%= site_comment.name %></td>
        <td><%= site_comment.mobile_phone %></td>
        <td><%= site_comment.content %></td>
        <td>
          <%= [site_comment.tel_phone, ', '].join('') unless site_comment.tel_phone.blank? %>
          <%= [site_comment.email, ', '].join('') unless site_comment.email.blank? %>
          <%= [site_comment.qq, ', '].join('') unless site_comment.qq.blank? %>
          <%= [site_comment.weixin, ', '].join('') unless site_comment.weixin.blank? %>
          <%= [site_comment.gender, ', '].join('') unless site_comment.gender.blank? %>
          <%= [site_comment.birth, ', '].join('') unless site_comment.birth.blank? %>
          <%= [site_comment.address, ', '].join('') unless site_comment.address.blank? %>
          <%= [site_comment.hobby, ', '].join('') unless site_comment.hobby.blank? %>
          <%= [site_comment.content2, ', '].join('') unless site_comment.content2.blank? %>
          <%= [site_comment.content3, ', '].join('') unless site_comment.content3.blank? %>
        </td>
        <td><%= distance_of_time_in_words_to_now(site_comment.created_at) %>前</td>
        <td><%= link_to '删除', site_comment, method: :delete, data: { confirm: '删除以后不能再恢复了，你确定要删除吗?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr/>
<%= will_paginate @site_comments %>
<br>
<%= link_to sites_path, class: 'btn btn-meflat icon-right' do %>
  返回 <i class="fa fa-arrow-up"></i>
<% end %>

app/views/site_comments/new.html.erb
<%= render 'theme_one' %>

app/views/site_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Site:</strong>
  <%= @site_comment.site %>
</p>

<p>
  <strong>Template page:</strong>
  <%= @site_comment.template_page %>
</p>

<p>
  <strong>Name:</strong>
  <%= @site_comment.name %>
</p>

<p>
  <strong>Mobile phone:</strong>
  <%= @site_comment.mobile_phone %>
</p>

<p>
  <strong>Tel phone:</strong>
  <%= @site_comment.tel_phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @site_comment.email %>
</p>

<p>
  <strong>Qq:</strong>
  <%= @site_comment.qq %>
</p>

<p>
  <strong>Weixin:</strong>
  <%= @site_comment.weixin %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @site_comment.gender %>
</p>

<p>
  <strong>Birth:</strong>
  <%= @site_comment.birth %>
</p>

<p>
  <strong>Address:</strong>
  <%= @site_comment.address %>
</p>

<p>
  <strong>Hobby:</strong>
  <%= @site_comment.hobby %>
</p>

<p>
  <strong>Content:</strong>
  <%= @site_comment.content %>
</p>

<p>
  <strong>Content2:</strong>
  <%= @site_comment.content2 %>
</p>

<p>
  <strong>Content3:</strong>
  <%= @site_comment.content3 %>
</p>

<p>
  <strong>Status:</strong>
  <%= @site_comment.status %>
</p>

<p>
  <strong>Updated by:</strong>
  <%= @site_comment.updated_by %>
</p>

<p>
  <strong>Note:</strong>
  <%= @site_comment.note %>
</p>