config/routes.rb
require 'sidekiq/web'

TmCard::Application.routes.draw do

  resources :resource_musics

  namespace :app do
    get "site/new"
    post "site/create"
    get "site/ajax_get_member"
    get "site/preview"
  end
  
  get '/home/dialog_banner'
  get '/home/dialog_music'
  resources :site_images do 
    collection {post :sort}
    collection {get :app}
    collection {get :meitu_load}
    collection {post :meitu_upload}
  end

  resources :members do
    collection {get :new_token}
    collection {post :verify_token}
  end

  resources :site_comments #for show on client
  resources :site_pages

  resources :sites do 
    resources :site_steps
    resources :site_comments #for admin manage
    collection do
      post :send_sms
    end
    get 'preview'
    get 'themes'
    get 'payment'
    post 'set_theme'
    post 'verify_payment_token'
    post :alipay_notify
  end
  namespace :sites do
    post "temp_form_update"
  end
  
  match '/s-:site_id(/p-:id)', to: "s#index", via: :get
  match '/templates(/page/:page)', to: "home#templates", via: :get, as: 'templates'
  match '/templates(/page/:page)', to: "home#templates", via: :get, as: 'ts'
  match '/templates/:id', to: "home#template", via: :get, as: 'template'
  match '/search(/page/:page)', to: "home#search", via: :get, as: 'search'
  match '/case(/page/:page)', to: "home#case", via: :get, as: 'case'
  match '/top(/:q)(/page/:page)', to: "home#top", via: :get, as: 'top'
  match '/biz(/page/:page)', to: "home#biz", via: :get, as: 'biz'
  match '/blog(/page/:page)', to: "home#blog", via: :get, as: 'blog'
  match '/post/:id', to: "home#post", via: :get, as: 'post'
  match '/pricing', to: "home#pricing", via: :get, as: 'pricing'
  match '/vip', to: "home#vip", via: :get, as: 'vip'
  match '/video', to: "home#video", via: :get, as: 'video'
  match '/zhuanpan_json/:id/:key', to: "home#zhuanpan_json", via: :get, as: 'zhuanpan_json'
  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: "omniauth_callbacks"}
  resources :users
  authenticate :user, lambda { |u| u.has_role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/resource_music.rb
class ResourceMusic < ActiveRecord::Base
  belongs_to :site

  has_attached_file :asset, :path => "musics/:class/:attachment/:id.:extension"
  validates :asset, :attachment_presence => true
  validates_attachment_size :asset, :less_than => 10.megabytes
  validates_attachment_content_type :asset,
    :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]

  after_create :expire_cache
  after_destroy :expire_cache

  def self.get_my_musics(current_session)
    if current_session.class.to_s == "User"
      where(user_id: current_session.id)
    else
      where(member_id: current_session.id)
    end
  end

  private
    #cache
    def expire_cache
      site = self.site
      cache_paths = []
      cache_paths << File.join(Rails.root, 'public', 'page_cache', 's-' + site.short_title + '.html')
      site.site_pages.each do |site_page|
        cache_paths << File.join(Rails.root, 'public', 'page_cache', "s-#{site.short_title}", "p-#{site_page.short_title}.html")
      end
      cache_paths.each do |path|
        if File.exist?(path)
          FileUtils.rm_rf path
        end
      end
    end
  
end

app/controllers/resource_musics_controller.rb
class ResourceMusicsController < ApplicationController
  before_action :set_resource_music, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_auth

  # GET /resource_musics
  # GET /resource_musics.json
  def index
    @resource_musics = ResourceMusic.all
  end

  # GET /resource_musics/1
  # GET /resource_musics/1.json
  def show
  end

  # GET /resource_musics/new
  def new
    @resource_music = ResourceMusic.new
  end

  # GET /resource_musics/1/edit
  def edit
  end

  # POST /resource_musics
  # POST /resource_musics.json
  def create
    @resource_music = ResourceMusic.new(resource_music_params)
    @resource_music.user_id = current_user.id if current_user
    @resource_music.member_id = current_member.id if current_member

    respond_to do |format|
      if @resource_music.save
        @resource_music.url = @resource_music.asset.url
        if @resource_music.name.blank?
          begin
            @resource_music.name = @resource_music.asset.url.sub(/.*\/(.*)\.\w+$/, '\1')
          rescue
            @resource_music.name = @resource_music.id
          end
        end
        @resource_music.save

        format.html { redirect_to @resource_music, notice: '音乐上传成功.' }
        format.json { render action: 'show', status: :created, location: @resource_music }
      else
        format.html { render action: 'new' }
        format.json { render json: @resource_music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resource_musics/1
  # PATCH/PUT /resource_musics/1.json
  def update
    authorize!(@resource_music)

    respond_to do |format|
      if @resource_music.update(resource_music_params)
        format.html { redirect_to @resource_music, notice: 'Resource music was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @resource_music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resource_musics/1
  # DELETE /resource_musics/1.json
  def destroy
    authorize!(@resource_music)
    @resource_music.destroy
    respond_to do |format|
      format.html { redirect_to resource_musics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource_music
      @resource_music = ResourceMusic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_music_params
      params.require(:resource_music).permit(:name, :url, :asset, :site_id)
    end
end

app/helpers/resource_musics_helper.rb
module ResourceMusicsHelper
end

app/views/resource_musics/_form.html.erb
<%= simple_form_for(@resource_music, html: { :multipart => true }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :site_id, as: :hidden, input_html: { value: params[:site_id]} %>
    <%= f.input :name %>
    <%= f.input :asset, as: :file, label: false %>
  </div>

  <div class="form-actions">
    <%= button_tag(type: 'submit', data: { disable_with: "正在上传,请耐心等待..." }, class: "btn btn-meflat icon-left") do %>
      <i class="fa fa-location-arrow"></i> 上 传
    <% end %>       
  </div>
<% end %>

app/views/resource_musics/create.html.erb
<h1>ResourceMusics#create</h1>
<p>Find me in app/views/resource_musics/create.html.erb</p>

app/views/resource_musics/edit.html.erb
<h1>Editing resource_music</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource_music %> |
<%= link_to 'Back', resource_musics_path %>

app/views/resource_musics/index.html.erb
<h1>Listing resource_musics</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Name</th>
      <th>Url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resource_musics.each do |resource_music| %>
      <tr>
        <td><%= resource_music.user %></td>
        <td><%= resource_music.name %></td>
        <td><%= resource_music.url %></td>
        <td><%= link_to 'Show', resource_music %></td>
        <td><%= link_to 'Edit', edit_resource_music_path(resource_music) %></td>
        <td><%= link_to 'Destroy', resource_music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource music', new_resource_music_path %>

app/views/resource_musics/new.html.erb
<h1>上传音乐文件</h1>

<%= render 'form' %>

app/views/resource_musics/show.html.erb
<h3>音乐上传成功!</h3>
<p>
复制以下链接添加到背景音乐栏：</p>
<p class="text-success"><%= @resource_music.asset.url %></p>