config/routes.rb
require 'sidekiq/web'

TmCard::Application.routes.draw do

  resources :resource_musics

  namespace :app do
    get "site/new"
    post "site/create"
    get "site/ajax_get_member"
    get "site/preview"
  end
  
  get '/home/dialog_banner'
  get '/home/dialog_music'
  resources :site_images do 
    collection {post :sort}
    collection {get :app}
    collection {get :meitu_load}
    collection {post :meitu_upload}
  end

  resources :members do
    collection {get :new_token}
    collection {post :verify_token}
  end

  resources :site_comments #for show on client
  resources :site_pages

  resources :sites do 
    resources :site_steps
    resources :site_comments #for admin manage
    collection do
      post :send_sms
    end
    get 'preview'
    get 'themes'
    get 'payment'
    post 'set_theme'
    post 'verify_payment_token'
    post :alipay_notify
  end
  namespace :sites do
    post "temp_form_update"
  end
  
  match '/s-:site_id(/p-:id)', to: "s#index", via: :get
  match '/templates(/page/:page)', to: "home#templates", via: :get, as: 'templates'
  match '/templates(/page/:page)', to: "home#templates", via: :get, as: 'ts'
  match '/templates/:id', to: "home#template", via: :get, as: 'template'
  match '/search(/page/:page)', to: "home#search", via: :get, as: 'search'
  match '/case(/page/:page)', to: "home#case", via: :get, as: 'case'
  match '/top(/:q)(/page/:page)', to: "home#top", via: :get, as: 'top'
  match '/biz(/page/:page)', to: "home#biz", via: :get, as: 'biz'
  match '/blog(/page/:page)', to: "home#blog", via: :get, as: 'blog'
  match '/post/:id', to: "home#post", via: :get, as: 'post'
  match '/pricing', to: "home#pricing", via: :get, as: 'pricing'
  match '/vip', to: "home#vip", via: :get, as: 'vip'
  match '/video', to: "home#video", via: :get, as: 'video'
  match '/zhuanpan_json/:id/:key', to: "home#zhuanpan_json", via: :get, as: 'zhuanpan_json'
  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: "omniauth_callbacks"}
  resources :users
  authenticate :user, lambda { |u| u.has_role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout :resolve_layout

  caches_page :index, :templates, :template, :pricing, :post
  
  def index
    #render text: params and return
  end

  def templates
    @cates = Templates::Cate.all
    @templates = Templates::Template.where(is_published: true).order("updated_at DESC").paginate(page: params[:page] || 1, per_page: 12)
  end

  def template
    @template = Templates::Template.find(params[:id])
  end

  def case
    @templates = Templates::Template.where("cate_id in (1,2)").order("updated_at DESC")
    @last_template = @templates.pop #use for filter style
    @sites = Site.sites_has_images.where("sites.status IS NULL OR sites.status not in('vip', 'thief')").paginate(page: params[:page] || 1, per_page: 12)
  end

  #案例精选
  #params: personal, business
  def top
    if params[:q] == 'p' || params[:q] == 'personal'
      @sites = Site.joins(:site_payment).personal.where("sites.status in('vip', 'vip-recommend') OR site_payments.state = 'completed'").order("id desc").page(params[:page])
    elsif params[:q] == 'b' || params[:q] == 'business'
      @sites = Site.joins(:site_payment).business.where("sites.status in('vip', 'vip-recommend') OR site_payments.state = 'completed'").order("id desc").page(params[:page])
    else
      @sites = Site.joins(:site_payment).where("sites.status in('vip', 'vip-recommend') OR site_payments.state = 'completed'").order("id desc").page(params[:page])
    end
  end

  #高级定制案例
  def biz
    @sites = BizSite.order("id DESC").page(params[:page])
  end

  def vip
    if current_session
      redirect_to new_site_path(template_id: params[:template_id], typo: 'business')
    end

    @show_contact = false #this var is for turn off footer contact form, used in layouts/_contact.html.erb
    @template = Templates::Template.find_by(id: params[:template_id])
    #render text: params and return
  end

  def pricing

  end

  def search

  end

  #post list
  def blog
    @posts = Admin::Page.joins(:channel).where("admin_channels.short_title = ?", 'wedxt').order("updated_at DESC").paginate(page: params[:page], per_page: 9)
  end

  def post
    @post = Admin::Page.find_by(short_title: params[:id])
  end

  def video
    @posts = Admin::Page.joins(:channel).where("admin_channels.short_title = ?", 'video').order("updated_at DESC").paginate(page: params[:page], per_page: 9)
  end
  
  #大转盘需要调用的action: 返回json数据，给js调用
  #params: site_page_id, key
  def zhuanpan_json
    # status 值：
    # 0 -> 亲，活动还未开始啦!
    # 1 -> 活动进行中: 抽奖并中奖
    # 2 -> 活动进行中：抽奖未中奖
    # 3 -> 今日奖品已经领完，明天继续哦！
    # 4 -> 亲，活动已经结束啦!
    @site_page = SitePage.find(params[:id])

    #状态获取
    status = case SitePageKeystore.value_for(@site_page, 'open_toggle')
    when '活动进行中'
      2
    when '活动未开始'
      0
    when '活动已结束'
      4
    else
      2
    end

    #获取用户设定的奖品总数
    prize_obj = SitePageKeystore.get(@site_page.id, 'prize_count')
    prize_count = prize_obj.value.to_i || 50
  
    #获取预计抽奖人数
    person_obj = SitePageKeystore.get(@site_page.id, 'person_count')
    person_count = person_obj.value.to_i || 100

    #计算中奖概率
    rate = prize_count/(person_count + 0.1)

    #获取已抽奖次数
    zhuan_obj = SitePageKeystore.get(@site_page.id, 'zhuan_count')
    if zhuan_obj.nil?
      key = CommonKey.get('zhuan_count')
      CommonKey.put('zhuan_count', 0) if key.nil?
      SitePageKeystore.put(@site_page.id, 'zhuan_count', 0)
      zhuan_obj = SitePageKeystore.get(@site_page.id, 'zhuan_count')
    end
    zhuan_count = zhuan_obj.value.to_i
    SitePageKeystore.put(@site_page.id, 'zhuan_count', zhuan_count + 1)

    status = 4 if zhuan_count >= person_count #次数已经抽完

    #获取中奖次数
    coupon_obj = SitePageKeystore.get(@site_page.id, 'coupon_count')
    if coupon_obj.nil?
      key = CommonKey.get('coupon_count')
      CommonKey.put('coupon_count', 0) if key.nil?
      SitePageKeystore.put(@site_page.id, 'coupon_count', 0)
      coupon_obj = SitePageKeystore.get(@site_page.id, 'coupon_count')
    end
    coupon_count = coupon_obj.value.to_i

    status  = 3 if coupon_count >= prize_count && status != 4 #奖品已完

    # 奖项数组 
    # 是一个二维数组，记录了所有本次抽奖的奖项信息， 
    # 其中id表示中奖等级，prize表示奖品，v表示中奖概率。 
    # 注意其中的v必须为整数，你可以将对应的 奖项的v设置成0，即意味着该奖项抽中的几率是0， 
    # 数组中v的总和（基数），基数越大越能体现概率的准确性。 
    # 本例中v的总和为100，那么平板电脑对应的 中奖概率就是1%， 
    # 如果v的总和是10000，那中奖概率就是万分之一了。 

    # goods_id: 
    # 8个值分别对应8格转盘的8个格子，其中3，7格为默认未中奖格，其他格为有奖格
    # 1 -> 奖品1
    # 2 -> 奖品2
    # 3 -> 未中奖
    # 4 -> 奖品3
    # 5 -> 奖品4
    # 6 -> 奖品5
    # 7 -> 未中奖
    # 8 -> 奖品6
    failed_count = (50/rate).to_i - 50 #预设中奖个数为50， 则根据中奖概率计算出未中奖个数
    prize_hash = {   
      0 => {'id'=>1,'prize'=> SitePageKeystore.value_for(@site_page, 'good1'),'v'=>1},   
      1 => {'id'=>2,'prize'=> SitePageKeystore.value_for(@site_page, 'good2'),'v'=>2},  
      2 => {'id'=>8,'prize'=> SitePageKeystore.value_for(@site_page, 'good3'),'v'=>5},
      3 => {'id'=>4,'prize'=> SitePageKeystore.value_for(@site_page, 'good4'),'v'=>10},  
      4 => {'id'=>5,'prize'=> SitePageKeystore.value_for(@site_page, 'good5'),'v'=>12},  
      5 => {'id'=>6,'prize'=> SitePageKeystore.value_for(@site_page, 'good6'),'v'=>20},
      6 => {'id'=>3,'prize'=> '没有抽中，感谢参与','v'=> failed_count/3},
      7 => {'id'=>7,'prize'=> '没有抽中，没准下次能抽到哦','v'=> failed_count/3*2},  
    }
    
    # 每次前端页面的请求，PHP循环奖项设置数组， 
    # 通过概率计算函数get_rand获取抽中的奖项id。 
    # 将中奖奖品保存在数组$res['yes']中， 
    # 而剩下的未中奖的信息保存在$res['no']中， 
    # 最后输出json个数数据给前端页面。 
    arr = {}
    prize_hash.each_pair do |key, val|
      arr[val['id']] = val['v']
    end
    rid = get_rand(arr) #根据概率获取奖项id
    coupon = prize_hash[rid - 1] #抽中的奖项
    if status == 2 && ![3, 7].include?(coupon['id']) #中奖了
      SitePageKeystore.put(@site_page.id, 'coupon_count', coupon_count + 1)
      status = 1
    end
    
    if status == 1 #中奖了
      render json: {status: status, goods_id: coupon['id'], message: coupon['prize'], Coupon: {grade: coupon['id']}}
    else #没中奖
      render json: {status: status}
    end
  end

  # 
  #  经典的概率算法， 
  #  $proArr是一个预先设置的数组， 
  #  假设数组为：array(100,200,300，400)， 
  #  开始是从1,1000 这个概率范围内筛选第一个数是否在他的出现概率范围之内，  
  #  如果不在，则将概率空间，也就是k的值减去刚刚的那个数字的概率空间， 
  #  在本例当中就是减去100，也就是说第二个数是在1，900这个范围内筛选的。 
  #  这样 筛选到最终，总会有一个数满足要求。 
  #  就相当于去一个箱子里摸东西， 
  #  第一个不是，第二个不是，第三个还不是，那最后一个一定是。 
  #  这个算法简单，而且效率非常高， 
  #  pro_hash = {id => v, 1 => 1, 2 => 30} 
  def get_rand(pro_hash)
      result = nil
      #概率数组的总概率精度  
      pro_sum = pro_hash.values.inject{|sum,x| sum + x }
      #概率数组循环
      pro_hash.each_pair do |key, pro_cur|
        rand_num = 1 + rand(pro_sum)
        if rand_num <= pro_cur
          result = key
          break
        else
          pro_sum -= pro_cur
        end
      end
      result
  end

  #用于page_steps中对话框扩展： 选择封面、选择音乐。
  #这些特殊的内容，不放在tm_admin中。

  #在弹出窗口的链接中如果想要显示该页面上传的图片，在需要传递site_page参数，用于获取site_page下面的图片列表：
  #<a data-target="#bannerModal" data-toggle="modal" href="/home/dialog_banner?site_page_id=<%=@site_page.id%>">
  # url: '/home/dialog_banner?site_page_id=' + @site_page.id.to_s
  def dialog_banner
   site_page = SitePage.find_by(id: params[:site_page_id])
   @site_images = site_page.site_images if site_page
   @site_images ||= []
  end

  def dialog_music
    @musics = ResourceMusic.where("user_id is null and member_id is null").order("updated_at DESC").page(params[:page])
    @my_musics = ResourceMusic.get_my_musics(current_session)
  end

  private
    def resolve_layout
      case action_name
      when /dialog_.*/ 
        false
      else
        "application"
      end
    end

end

app/views/home/choose_banner.html.erb
暂时不考虑这个怎么做
-》 名片针对每个学校的封面搜索。。。

app/views/home/portfolio.html.erb
<% title "模板-维斗喜帖模板|喜帖模板,请帖模板,请柬模板|二维码请柬模板|手机请帖模板|微信喜帖模板" %>
<% meta_description "维斗喜帖提供数十款漂亮的结婚请帖模版，免费试用，支持手持互动，精美的微信请帖模版，手机动态请帖模版，微信电子相册。" %>

<div class="container">
  <header class="section-header text-center">
    <h1 class="scrollimation scale-in">应用模板</h1>
    <p>选择你喜欢的模板，点击查看详细案例.<br/> 每个模板都有不同的内容和风格要求，请按照每个模板的提示准备素材.</p>
  </header>
</div><!--End portfolio header -->

<!-- ==============================================
PORTFOLIO
=============================================== --> 
<div id="projects-wrapper" class="container masonry-wrapper scrollimation fade-in">

  <div id="projects-container">
    <% @templates.each do |template| %>
      <% demo_images = get_demo_image_list(template, 'demo_img') %>
      <!-- ==============================================
      SINGLE PROJECT ITEM
      =============================================== --> 
      <article class="project-item web-design">
        
        <img class="img-responsive project-image" src="<%= demo_images.shift %>"  alt="<%= template.title %>"><!--Project thumb -->
        
        <div class="hover-mask">
          <h2 class="project-title"><%= template.title %></h2><!--Project Title -->
          <p><%= template.cate.title %></p><!--Project Subtitle -->
        </div>
        
        <!--==== Project Preview HTML ====-->
        <div class="sr-only project-description" 
          data-category="<%= template.cate.title %>" 
          data-date="<%= get_date(template.updated_at) %>" 
          data-client="<%= template.keywords %>" 
          data-descr="<%= template.summary %>" 
          data-images="<%= demo_images.join(',') %>"
        >
          <%= raw template.description %>
          <div class="">
            <h3 class="bottom_bordered">最新发布</h3>
            <div class="row">
              <% template.recent_sites.each do |site| %>
                <div class="col-sm-6 col-md-3">
                  <div class="thumbnail">
                    <img src="<%= get_first_site_image_url(site) %>" />
                    <!--<img src="http://qrickit.com/api/qr?d=<%=get_site_url(site)%>&fgdcolor=000000&bgdcolor=F1678D&qrsize=120&t=p&e=m"> -->
                    <div class="caption text-center">
                      <p><small><a href="<%= site_preview_path(site)%>" target="_blank"><%= site.title.to_s.truncate(10) %></a></small></br><%= distance_of_time_in_words_to_now(site.updated_at) %>前</p>
                      <p>
                        <a href="<%= site_preview_path(site)%>" target="_blank" class="btn btn-default">预览</a>
                      </p>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <p>怎么样，是不是觉得很赞？<br/>其实制作很简单，填一个表格，传几张图即可完成，超级方便！</p>
          <p class="text-right">
            <%= link_to new_site_path(template_id: template.id),  data: {confirm: '确定要使用该模板？'}, class: "btn btn-meflat icon-right" do %>
              我要制作 <i class="fa fa-arrow-right"></i>
            <% end %>
          </p>
        </div>
        
      </article>
      <div class="col-md-4 project-item-btn"><p class="text-center">
        <%= link_to '快速创建', app_site_new_path(template_id: template.id), class: 'btn btn-meflat' %>
      </p></div>
      <!-- ==============================================
      END PROJECT ITEM
      =============================================== -->           
    <% end %>            
  </div><!-- End projects --> 
  
</div><!-- End container --> 

<!-- ==============================================
PROJECT PREVIEW MODAL (Do not alter this markup)
=============================================== --> 
<div id="project-modal" class="modal fade">

  <div class="modal-dialog">
  
    <div class="modal-content">
    
      <div class="modal-header">
      
        <div class="container">
        
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          
          <h1 id="hdr-title" class="text-center"></h1>
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <div class="image-wrapper">
                <img class="img-responsive" src="/assets/chrome.png" alt="">
                <div class="loader"></div>
                <div class="screen"></div>
              </div>
            </div>
          </div>
        </div>
        
      </div>
      
      <div class="modal-body">
        <div class="container">
          <div class="row">
            <div id="project-sidebar" class="col-md-3">
              <h2 id="sdbr-title"></h2>
              <p id="sdbr-category"></p>
              <p id="sdbr-date"></p>
              <p id="sdbr-client"></p>
              <p id="sdbr-link"><a href="#link" target="_blank"></a></p>
              <p id="sdbr-descr"></p>
            </div>
            <div id="project-content" class="col-md-8 col-md-offset-1">
            </div>
          </div>
          
        </div>
      </div><!-- End modal-body -->
      
    </div><!-- End modal-content -->
    
  </div><!-- End modal-dialog -->
</div><!-- End project-modal -->

app/views/home/post.html.erb
<% title "#{@post.title}-维斗喜帖" %>
<% meta_keywords "#{@post.title},维斗喜帖出品,请柬,漂亮微信请帖,商务请帖,二维码请柬,微信请柬,电子喜帖,结婚喜帖" %>
<% meta_description "#{@post.title}|维斗喜帖，漂亮的电子喜帖、商务请柬、微信请帖、二维码请柬。" %>

<div class="row">
  <div id="project-sidebar" class="col-md-3 hidden-xs">
    <h3 id="sdbr-title">
    <img src="http://qr.liantu.com/api.php?text=<%="http://wedxt.com/post/#{@post.short_title}"%>&w=200" />
      <br/><small>扫一扫，在手机上浏览</small>
    </h3>

    <p id="sdbr-category"><%= @post.keywords %></p>
    <p id="sdbr-date"><%= get_date(@post.updated_at) %></p>
    <p id="sdbr-link"><a href="/blog">返回</a></p>

    <%= render partial: 'layouts/duoshuo', locals: {post: @post} %>
  </div>
  <div id="project-content" class="col-md-8 col-md-offset-1">
    <article>
      <h1><%= @post.title %></h1>
      <hr/>
      <%= raw @post.content %>
    </article>
    <p class="text-right"><a class="btn btn-meflat icon-right" href="/blog"><i class="fa fa-arrow-left"></i> 返回</a></p>
  </div>
</div>

app/views/home/template.html.erb
<% title "#{@template.title}-微信请帖模板,维斗喜帖出品" %>
<% meta_keywords "#{@template.title},维斗喜帖出品,请柬模板,漂亮微信请帖模板,商务请帖模板,二维码请柬模板,微信请柬模板,电子喜帖模板,结婚喜帖模板" %>
<% meta_description "#{@template.title}|维斗喜帖，漂亮的商务请帖、微信请帖、二维码请柬。" %>
<!-- ==============================================
PROJECT PREVIEW MODAL (Do not alter this markup)
=============================================== --> 
<div id="project-modal" class=" " >

  <div class="modal-dialog">
  
    <div class="modal-content">
    
      <div class="modal-header">
      
        <div class="container">
          <h1 id="hdr-title" class="text-center"><%= @template.title %></h1>
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <div class="image-wrapper">
                <%= image_tag('chrome.png', alt: '维斗喜帖桌面背景', class: "img-responsive") %>
                <div class="loader" ></div>
                <div class="screen flexslider"><div class="flex-viewport" ><ul class="slides">
                <% get_demo_image_list(@template, 'demo_img', 'index').each do |img| %>
                  <li><img src="<%= img %>" alt="<%= @template.title %>" draggable="false"></li>
                <% end %>
                </ul></div><ul class="flex-direction-nav"><li><a class="flex-prev" href="#"><i class="fa fa-angle-left"></i></a></li><li><a class="flex-next" href="#"><i class="fa fa-angle-right"></i></a></li></ul></div>
              </div>
            </div>
          </div>
        </div>

      </div>
      
      <div class="modal-body">
        <div class="container">
          <div class="row">
            <div id="project-sidebar" class="col-md-3">
              <h2 id="sdbr-title">
                <% unless @template.property == 'free' %>
                  <%= link_to app_site_new_path(template_id: @template.id, typo: 'personal'), class: 'btn btn-block btn-meflat icon-right', style: 'height: 70px' do %>
                    开始制作<br/><small>(免费试用)</small>
                  <% end %>

                <% else %>
                  <%= link_to app_site_new_path(template_id: @template.id, typo: 'personal'), class: 'btn btn-meflat icon-right', style: 'height: 70px' do %>
                    免费制作<i class="fa fa-arrow-right"></i>
                  <% end %>
                <% end %>
              </h2>
              <p id="sdbr-category"><%= @template.cate.title %></p>
              <p id="sdbr-date"><%= get_date(@template.updated_at) %></p>
              <p id="sdbr-client"><%= @template.keywords %></p>
              <p id="sdbr-descr"><%= @template.summary %></p>
              <p id="sdbr-price"><a href="/pricing">价格说明</a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="/users/sign_in">会员通道</a></p>
            </div>
            <div id="project-content" class="col-md-8 col-md-offset-1">
              <%= raw @template.description %>
              <div class="">
                <h3 class="bottom_bordered"><%= @template.title %>案例展示</h3>
                <div class="row">
                  <% @template.recommend_sites(6).each do |site| %>
                    <% img_url = get_first_site_image_url(site) %>
                    <% next if img_url.nil? %>
                    <div class="col-xs-6 col-md-4">
                      <div class="thumbnail recommend-thumbnail">
                      <%= image_tag qiniu_image_path(img_url, :thumbnail => '200x300>', :quality => 80), class: "img-responsive",  alt: site.title %>

                        <div class="caption text-center">
                          <p><a href="<%= site_preview_path(site)%>" target="_blank"><%= site.title.to_s.truncate(9) %></a></p>
                          <p>
                            <a href="<%= site_preview_path(site)%>" target="_blank" class="btn btn-info">点击预览</a>
                          </p>
                        </div>
                      </div>
                  </div>
                  <% end %>
                </div>
              </div>
              <p>怎么样，是不是觉得很赞？<br>其实制作很简单，填一个表格+传几张图即可完成，还可以通过手机登录后台不断完善，超级方便！</p>
              <p class="text-right">
                <%= link_to new_site_path(template_id: @template.id, typo: 'personal'), class: 'btn btn-meflat icon-right' do %>
                  开始制作 <i class="fa fa-arrow-up"></i>
                <% end %>      
              </p>
              <p class="text-right">
                <%= link_to '/post/help' do%>
                  <i class="fa fa-info"></i> 使用帮助
                <% end %>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <%= link_to templates_path do%>
                  <i class="fa fa-reply"></i> 返回
                <% end %>
              </p>
            </div>
          </div><!-- end row-->
        </div>
      </div><!-- End modal-body -->
      
    </div><!-- End modal-content -->
    
  </div><!-- End modal-dialog -->
</div>
<!-- ==============================================
PROJECT PREVIEW MODAL END
=============================================== --> 

app/views/home/templates.bak.html.erb
<% title "模板-维斗喜帖模板|喜帖模板,请帖模板,请柬模板|二维码请柬模板|手机请帖模板|微信喜帖模板" %>
<% meta_description "维斗喜帖提供数十款漂亮的结婚请帖模版，免费试用，支持手持互动，精美的微信请帖模版，手机动态请帖模版，微信电子相册。" %>

<!-- ==============================================
Blog
=============================================== -->
<section id="blog" class="white-bg padding-top-bottom">
  <div class="container">
    <div class="row blog">
      <% @templates.each do |template| %>
        <% demo_images = get_demo_image_list(template, 'demo_img') %>
        <div class="col-md-4 col-sm-6 item scrollimation fade-up">
          <div class="icon">
            <%= link_to template_path(template) do %>
              <img class="img-responsive img-center" src="<%= demo_images.shift %>" alt="<%= template.title %>" />
            <% end %>
          </div>        
          <h2><%= link_to template.title, template_path(template) %></h2>
          <div class="text-center">
            <%= link_to app_site_new_path(template_id: template.id), class: 'btn btn-meflat icon-right' do %>
              我要制作 <i class="fa fa-arrow-up"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>  
  </div>
</section>

app/views/home/top.html.erb
<% title "精选案例-维斗喜帖案例|喜帖,请帖,请柬|二维码请柬案例|手机请帖案例|微信请帖案例" %>
<% meta_keywords "喜帖案例,请帖案例,请柬案例,漂亮微信请帖案例,商务请帖案例,二维码请柬案例,微信请柬案例,电子喜帖案例,结婚喜帖案例" %>
<% meta_description "维斗喜帖每天都有数十款喜帖案例生成，包括二维码请帖制作案例，微信喜帖案例，电子请帖案例，微相册案例；分分钟创建，惊艳朋友圈。" %>

<!-- ==============================================
Top
=============================================== --> 
<section id="top">
  
  <div class="container">
    <div class="row">
      <% @sites.each do |site| %>
        <% img_url = get_first_site_image_url(site) %>
        <% next if img_url.nil? %>
        <% template = site.template %>
        <div class="col-sm-6 col-md-3">
          <div class="thumbnail biz-thumbnail">
            <a href="<%= site_preview_path(site)%>" target="_blank">
              <%= image_tag qiniu_image_path(img_url, thumbnail: 'x320', crop: '!320x-0a0', quality: 80), class: "img-responsive project-image",  alt: site.title %>
            </a>
            <div class="caption text-center" id="caption_<%=site.id%>">
              <p>
                <a href="<%= site_preview_path(site)%>" target="_blank"><%= site.title.to_s.truncate(12) %></a><br/>
                【<%= link_to template.title, "/templates/#{template.id}", style: 'color: gray;' %>】
                <a href="<%= get_site_url(site) %>" id="<%= site.id %>" target="_blank" title="扫描二维码" data-title="<%= site.title %>" onmouseover="javascript: show_qr(<%= site.id %>);" style="font-size: 24px; color: #94daf0;"> <i class="fa fa-qrcode"> </i> </a>
              </p>
            </div>
          </div>
        </div>
      <% end %>
        <div class="col-sm-6 col-md-3">
          <div class="thumbnail">
            <%= image_tag asset_path('placeholder1.jpg'), style: "width: 100%; max-height: 320px;" %>
            <div class="caption text-center">
              <p><a href="/case">更多案例...</a></p>
            </div>
          </div>
        </div>
    </div>
  </div>
  <div class="text-right">
    <%= will_paginate @sites %>
  </div>
</section>


<!-- qrModal start-->
<div id="qrModal" class="modal <%= ie_browser? ? '' : 'fade' %>">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <div class="container">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h1 id="hdr-title" class="text-center">扫描二维码</h1>
        </div>
      </div>
      <div class="modal-body text-center" id="qrBody">
        
      </div><!-- End modal-body -->
    </div><!-- End modal-content -->
  </div><!-- End modal-dialog -->
</div>
<!-- qrModal end-->

<script language="javascript">
  function show_qr(site_id){
    var site = $('#' + site_id);
    $('#qrModal').modal('toggle');
    $("#qrBody").html("<img src='http://qr.liantu.com/api.php?text=" + site.attr('href') + "&w=200' /><br/>"  + site.data('title') + "" );
  }
</script>