config/routes.rb
require 'sidekiq/web'

TmCard::Application.routes.draw do

  resources :resource_musics

  namespace :app do
    get "site/new"
    post "site/create"
    get "site/ajax_get_member"
    get "site/preview"
  end
  
  get '/home/dialog_banner'
  get '/home/dialog_music'
  resources :site_images do 
    collection {post :sort}
    collection {get :app}
    collection {get :meitu_load}
    collection {post :meitu_upload}
  end

  resources :members do
    collection {get :new_token}
    collection {post :verify_token}
  end

  resources :site_comments #for show on client
  resources :site_pages

  resources :sites do 
    resources :site_steps
    resources :site_comments #for admin manage
    collection do
      post :send_sms
    end
    get 'preview'
    get 'themes'
    get 'payment'
    post 'set_theme'
    post 'verify_payment_token'
    post :alipay_notify
  end
  namespace :sites do
    post "temp_form_update"
  end
  
  match '/s-:site_id(/p-:id)', to: "s#index", via: :get
  match '/templates(/page/:page)', to: "home#templates", via: :get, as: 'templates'
  match '/templates(/page/:page)', to: "home#templates", via: :get, as: 'ts'
  match '/templates/:id', to: "home#template", via: :get, as: 'template'
  match '/search(/page/:page)', to: "home#search", via: :get, as: 'search'
  match '/case(/page/:page)', to: "home#case", via: :get, as: 'case'
  match '/top(/:q)(/page/:page)', to: "home#top", via: :get, as: 'top'
  match '/biz(/page/:page)', to: "home#biz", via: :get, as: 'biz'
  match '/blog(/page/:page)', to: "home#blog", via: :get, as: 'blog'
  match '/post/:id', to: "home#post", via: :get, as: 'post'
  match '/pricing', to: "home#pricing", via: :get, as: 'pricing'
  match '/vip', to: "home#vip", via: :get, as: 'vip'
  match '/video', to: "home#video", via: :get, as: 'video'
  match '/zhuanpan_json/:id/:key', to: "home#zhuanpan_json", via: :get, as: 'zhuanpan_json'
  root :to => "home#index"

  devise_for :users, :controllers => {:registrations => "registrations", omniauth_callbacks: "omniauth_callbacks"}
  resources :users
  authenticate :user, lambda { |u| u.has_role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/app/site_controller.rb
#encoding: utf-8
class App::SiteController < ApplicationController
  include SHelper

  def new
    if params[:template_id].nil? || (@template = Templates::Template.find_by(id: params[:template_id])).nil?
      redirect_to portfolio_path, notice: t('notice.site.choose_template')
      return
    end
    if current_session
      redirect_to new_site_path(template_id: params[:template_id], typo: params[:typo])
    end
  end

  #"member"=>{"phone"=>"18080801080"}, 
  #"site"=>{"boy"=>"梁山伯", "girl"=>"祝英台", "date"=>"2014-07-18", "address"=>"成都锦江区滨江东路9号"}}
  def create
    #1. find or create member
    @member = get_member(member_params)
    if @member.nil?
      redirect_to app_site_new_path(params.merge!(template_id: site_params[:template_id])), alert: '你提供的手机号不正确，请重试' and return
    end
    get_session(@member)

    #2. create site
    @site = Site.new(title: site_params.delete(:title))
    @site.member_id = current_member.id if current_member
    @site.template_id = site_params[:template_id]
    @site.description = "我们定于#{params[:site][:date]}举行宴请典礼，敬请光临！"
    @site.typo = ['personal', 'business'].delete(site_params[:typo].to_s.downcase) || 'personal'

    respond_to do |format|
      if @site.save
        if @site.template.property == 'free'
          @site.set_free
        end
        #initialize default key-value
        params[:site].merge!(boy_phone: member_params[:auth_id])
        params[:site].merge!(girl_phone: member_params[:auth_id])
        params[:site].merge!(mobile_phone: member_params[:auth_id])
        params[:site].merge!(banner: '/banners/1.jpg')
        params[:site].merge!(music: '/musics/mp3/fanweiqi_zui-zhong-yao-de-jue-ding.mp3')
        params[:site].merge!(welcome: "各位亲朋好友：在这温馨浪漫，喜悦甜蜜的日子里我俩决定于#{params[:site][:date]}举行宴请典礼，届时敬备酒宴，欢迎您到来分享这份喜悦，您的光临将使我们的婚宴增添万分光彩!")
        params[:site].merge!(story: '1998年的夏天，两个年轻的学生背着一大堆的理想步入高一的学堂，在中学那座老旧的红墙教室里，他们第一次相遇；之后他俩成了相交甚好的同学，开启了一段冲往象牙塔的梦想之旅。')
        params[:site].merge!(wed_description: %{
<h5>07:00  新郎的接亲队伍准时出发到新娘家</h5>
  08:30  排好车队新人出发返回新房<br/>
<h5>17:00  宾客签到</h5>
<h5>18:00  婚礼仪式正式开始</h5>
  18:30  新人敬酒<br/>
  19:40  婚礼仪式结束，客人茶歇时间<br/>
          })
        #build site_page via template_page
        first_site_page = nil
        Templates::Page.where(template_id: @site.template_id).order("position ASC").each do |temp_page|

          #1. create site page
          site_page = @site.site_pages.create(
            site_id: @site.id, 
            template_page_id: temp_page.id,
            title: temp_page.title
          )
          #2. assign key value
          if params[:site].any? && temp_form = Templates::Keystore.get(temp_page, 'form')
            form_html = temp_form.value
            params[:site].each_pair do |key, value|
              if form_html =~ / name="site_page\[#{key}\]"/i
                val = params[:site].delete(key)
                SitePageKeystore.put(site_page.id, key, val) unless val.blank?
              end
            end
          end
          #3. get the first site page
          first_site_page ||= site_page
        end
        #add a comment
        SiteComment.create(site_id: @site.id, name: '维斗喜帖', content: '小维斗来过，提前送上一声祝福~')
        
        #send notice to admin
        # if Rails.env == 'production'
        #   SmsSendWorker.perform_async(ENV['ADMIN_PHONE'].split('|').join(','), "#{@site.user.try(:email) || @site.member.try(:auth_id)}创建了应用：#{get_site_url(@site)}")
        # end

        if mobile_device?
          format.html { redirect_to app_site_images_path(site_page_id: first_site_page.id), notice: t('notice.site.created') }
        else
          format.html { redirect_to site_site_steps_path(@site), notice: t('notice.site.created') }
        end
        format.json { render action: 'show', status: :created, location: @site }
      else
        format.html { render action: 'new', alert: '应用创建失败，请检查输入是否正确' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  def ajax_get_member
    auth_id = params[:auth_id].to_s.strip
    if auth_id.match(/^1[3456789]\d{9}$/)
      member = Member.find_by(auth_id: auth_id)
      if member.present? && member.sites.any?
        txt = %{
          <script>$('#memberModal').modal('toggle');</script>
          <div class="alert alert-info alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">关闭</span></button>
            <p>亲，小维斗检测到您已经在该网站创建了 <strong>#{member.sites.size.to_s}</strong> 个应用，为避免重复创建，请首先登录网站后台，然后再添加新应用.</p>
          </div
        }
        render text: txt and return
      end
    end
    render text: ''
  end

  def preview
  end

  private
    #login
    #{"auth_type"=>"phone", "auth_id"=>"12588885556"}
    def get_member(member_params)
      member = Member.find_by(auth_type: member_params[:auth_type], auth_id: member_params[:auth_id])
      return member if member.present?
      member = Member.new(member_params)
      unless member.save
        return nil
      end
      member
    end

    def member_params
      params.require(:member).permit(:auth_type, :auth_id)
    end

    def site_params
      params.require(:site).permit(:template_id, :typo, :title, :boy, :girl, :date, :address)
    end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  include SHelper
  #alipay notify 获得alipay返回过来的异步调用，添加下面一行，否则422错误
  skip_before_filter :verify_authenticity_token, :only => [:alipay_notify]
  #权限验证过滤掉alipay_notify
  before_filter :authenticate_auth, except: [:preview, :alipay_notify]
  before_action :set_site, only: [:show, :edit, :update, :destroy, :preview, :payment, :themes, :set_theme, :verify_payment_token]

  # GET /sites
  # GET /sites.json
  def index
    if current_user
      if current_user.id == 1 && current_user.email == 'master@inruby.com'
        @sites = Site.order("updated_at desc").page(params[:page] || 1)
      else
        @sites = current_user.sites.page(params[:page] || 1)
      end
    elsif current_member
      @sites = current_member.sites.page(params[:page] || 1)
    end
  end

  def preview
    
  end

  #用户付款页面
  #同时也用于支付宝回调，带参数。
  #  Parameters: {"id"=>"9", "buyer_email"=>"180xxxx0818", "buyer_id"=>"2081804692", "exterface"=>"trade_create_by_buyer", 
  # "is_success"=>"T", "logistics_fee"=>"0.00", "logistics_payment"=>"SELLER_PAY", "logistics_type"=>"DIRECT", 
  # "notify_id"=>"RqPnCoPT3K9%2FL4GdP4QUlJPCi0i", "notify_time"=>"2014-06-19 15:59:38", \
  # "notify_type"=>"trade_status_sync", "out_trade_no"=>"9", "payment_type"=>"1", "receive_address"=>"null", 
  # "seller_email"=>"kenrxxx@xx.com", "seller_id"=>"208566fwef3013", "subject"=>"账户充值：1.0", "total_fee"=>"1.00",
  #  "trade_no"=>"201407xx90469", "trade_status"=>"TRADE_FINISHED", "sign"=>"112e39xx9c059ea12210fe4b2", "sign_type"=>"MD5", "site_id"=>"8"}
  def payment
    @site_payment = @site.site_payment
    # callback_params = params.except(*request.path_parameters.keys)
    # if callback_params.any?
    #   render site_payment_path(@site), notice: "支付宝支付状态: #{callback_params[:trade_status]}" and return
    # end
  end
  
  # 支付宝异步消息接口
  # 注意：必须在服务器上正常运行才能测试，本地localhost阿里是不会自动post这个接口的
  def alipay_notify
    notify_params = params.except(*request.path_parameters.keys)
    # 先校验消息的真实性
    if Alipay::Notify.verify?(notify_params)
      # 获取交易关联的订单
      @payment = SitePayment.find params[:out_trade_no]

      case params[:trade_status]
      when 'WAIT_BUYER_PAY'
        # 交易开启
        @payment.update_attribute :trade_no, params[:trade_no]
        @payment.pend
      when 'TRADE_FINISHED'
        # 交易完成
        need_mail = @payment.pending?
        @payment.complete
        #SystemMailer.delay.payment_payment_success(@payment.id.to_s) if need_mail
      when 'TRADE_CLOSED'
        # 交易被关闭
        @payment.cancel
        #SystemMailer.delay.payment_cancel(@payment.id.to_s)
      when 'WAIT_SELLER_SEND_GOODS'
        # 买家完成支付
        @payment.pay
        # 虚拟物品无需发货，所以立即调用发货接口
        @payment.send_good
        #SystemMailer.delay.payment_payment_success(@payment.id.to_s)
      else
        # do nothing
      end

      #send notice to admin
      if Rails.env == 'production' && ['pending', 'completed'].include?(@payment.state)
        SmsSendWorker.perform_async(ENV['ADMIN_PHONE'].split('|').join(','), "【维斗喜帖】支付状态：#{@payment.state}, 应用: http://www.wedxt.com/sites/#{@payment.site_id}/preview")
      end

      #@payment.payment_notifies.create!(verify: true, payment_number: "p#{@payment.id}r#{rand(30034)}", payment_count: @payment.price, state: 'income', cate: '在线充值', status: params[:trade_status])
      # 成功接收消息后，需要返回纯文本的 ‘success’，否则支付宝会定时重发消息，最多重试7次。 
      render :text => 'success'
    else
      #@payment.payment_notifies.create!(verify: false, payment_number: "p#{@payment.id}r#{rand(30034)}", payment_count: @payment.price, state: 'income', cate: '在线充值', status: params[:trade_status])

      render :text => 'error'
    end
  end

  #验证激活码
  #1. 激活码是否有效
  #2. 
  def verify_payment_token
    #render text: params and return
    #{"code"=>"2faff2f", "commit"=>"验 证", "action"=>"verify_payment_token", "controller"=>"sites", "site_id"=>"21"}
    if payment_token = Payment::Token.active.where("code = ?", params[:code].strip).first
      #update payment_token
      payment_token.actived_by = current_session.id
      payment_token.actived_site_id = @site.id
      payment_token.status = 'inactive'
      payment_token.save
      #update site_payment
      site_payment = @site.site_payment
      site_payment.state = 'completed'
      site_payment.pay_type = 'token'
      site_payment.completed_at = Time.now
      site_payment.updated_by = current_session.id
      site_payment.note = "激活码验证"
      site_payment.save

      #send notice to admin
      if Rails.env == 'production' && current_session.id > 5
        SmsSendWorker.perform_async(ENV['ADMIN_PHONE'].split('|').join(','), "【维斗喜帖】#{current_session.try(:email) || current_session.try(:auth_id)}激活了应用：#{get_site_url(@site)}")
      end

      redirect_to site_path(@site), notice: t('notice.site.active_token')
    elsif Payment::Token.inactive.where("code = ?", params[:code].strip).first
      redirect_to site_payment_path(@site), alert: t('notice.site.inactive_token')
    else
      redirect_to site_payment_path(@site), alert: t('notice.site.invalid_token')
    end
  end

  #show themes list
  def themes
    #@site = Site.find(params[:site_id])
    @themes = Templates::Template.find_by(id: @site.template_id).try(:themes)
  end
  #set theme for this site
  #{"theme_id"=>"2", "action"=>"set_theme", "controller"=>"sites", "site_id"=>"8"}
  def set_theme
    authorize!(@site)

    @site.theme_id = params[:theme_id]
    @site.save
    redirect_to sites_path, notice: t('notice.site.set_theme')
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    
  end

  # GET /sites/new
  def new
    if params[:template_id].nil? || Templates::Template.find_by(id: params[:template_id]).nil?
      redirect_to templates_path, notice: t('notice.site.choose_template')
      return
    end
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)
    @site.user_id = current_user.id if current_user
    @site.member_id = current_member.id if current_member
    @site.typo = ['personal', 'business'].delete(params[:typo].to_s.downcase) || 'personal'

    respond_to do |format|
      if @site.save!
        if params[:typo] == 'business'
          @site.site_payment.price = ENV["PRICE_BUSINESS"]
          @site.site_payment.save!
        end
        if @site.template.property == 'free'
          @site.set_free
        end
        #build site_page via template_page
        Templates::Page.where(template_id: @site.template_id).order("position ASC").each do |temp_page|
          @site.site_pages.create(
            site_id: @site.id, 
            template_page_id: temp_page.id,
            title: temp_page.title)
        end
        #add a comment
        SiteComment.create(site_id: @site.id, name: '维斗喜帖', content: '小维斗来过，提前送上一声祝福~')
        
        #send notice to admin
        # if Rails.env == 'production'
        #   SmsSendWorker.perform_async(ENV['ADMIN_PHONE'].split('|').join(','), "#{@site.user.try(:email) || @site.member.try(:auth_id)}创建了应用：#{get_site_url(@site)}")
        # end
        #redirect
        format.html { redirect_to site_site_steps_path(@site), notice: t('notice.site.created') }
        format.json { render action: 'show', status: :created, location: @site }
      else
        format.html { render action: 'new' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    authorize!(@site)

    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to site_site_steps_path(@site), notice: t('notice.site.updated') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    authorize!(@site)

    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  def send_sms   
    #因为短信账户老是被盗用，所以暂时停用！

    # if ENV['SMS_BAO_USER'].nil? || ENV['SMS_BAO_PASSWORD'].nil? || ENV['SMS_MAX_CHARACTER_COUNT'].nil?
    #   raise "请配置短信发送接口的环境变量"
    # end
    # SmsSendWorker.perform_async(params[:mobile_phone], params[:content])
    # respond_to do |format|
    #   format.js {}
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find_by(id: params[:id])
      #for preview/themes/set_theme
      @site ||= Site.find_by(id: params[:site_id])
      not_found if @site.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:user_id, :member_id, :template_id, :short_title, :title, :description, :domain, :is_publiched, :is_comment_show, :updated_by, :note, :typo)
    end

    #expired, we used QRcode API to generate qrcode
    def generate_qrcode_bak(page)
      url = get_site_url(page)
      return if url.blank?
      qr = RQRCode::QRCode.new( url, :size => 6, :level => :h )
      png = qr.to_img # returns an instance of ChunkyPNG

      qr_dir = File.join(Rails.root, 'public', 'qrcode')
      FileUtils.mkdir_p qr_dir
      png_path = File.join(qr_dir, "#{page.id}.png")
      if File.exist? png_path
        #FileUtils.rm png_path
      else
        png.resize(120, 120).save(png_path)
      end     
    end

end

app/helpers/app/site_helper.rb
module App::SiteHelper
end

app/helpers/sites_helper.rb
module SitesHelper
  STATE = %w(opening pending paid completed canceled)
  def payment_state(site)
    site_payment = site.site_payment
    case site_payment.state
    when 'opening'; '等待付款'
    when 'pending'; '等待发货'
    when 'paid'; '等待收货'
    when 'completed'; '付款成功'
    when 'canceled'; '已经取消'
    when 'expired'; '已经过期'
    else '未知'
    end
  end
end

app/views/sites/edit.html.erb
<header class="section-header text-center">
  <h1 class="scrollimation scale-in"><%= title "修改应用" %></h1>
</header>

<div class="row services">
  <div class="col-sm-12 col-md-4 col-md-offset-5">
    <%= render 'form' %>
  </div>
</div>

 

app/views/sites/index.html.erb
<% if @sites.empty? %>
  <div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>欢迎<%=current_user.try(:email) || current_member.try(:auth_id)%>!</strong> 你还没有添加应用哦，<a href="/templates">点击这里</a>选择个喜欢的模板并创建.
  </div>
<% end %>

<%= link_to '创建新应用', new_site_path, class: 'btn btn-meflat' %>

<div class="row">
  <% @sites.each_with_index do |site, index| %>
    <div class="col-md-3 col-sm-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= get_short_content(site.title, 14) %><br/>
            <small>&lt;<%= site.template.title %>&gt;</small>
            </h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-6">
              <a href="<%= edit_site_path(site) %>" class="thumbnail pull-left">
                <% if img = get_first_site_image_url(site) %>
                  <img src="<%= get_first_site_image_url(site) %>" alt="<%= site.title %>" width="160px;" class="img-responsive">
                <% else %>
                  <img src="/assets/placeholder.jpg" alt="请上传640x960px大小照片" width="160px;" class="img-responsive" />
                <% end %>
              </a>
            </div>
            <div class="col-md-6">
             
              <%= link_to '编辑', edit_site_path(site), class: 'btn btn-default margin-top-sm' %>
              <% if  site.template.themes.any? %>
                <%= link_to '主题', site_themes_path(site), class: 'btn btn-default margin-top-sm' %>
              <% end %>
              <%= link_to '删除', site, method: :delete, data: { confirm: '删除以后，你所有的数据将丢失，而且无法找回，确定要删除?' }, class: 'btn btn-default margin-top-sm' %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <% if mobile_device? %>
                <%= link_to '预览', get_site_url(site), class: 'btn btn-info margin-top-sm' %>
              <% else %>
                <%= link_to '预览', site_preview_path(site), class: 'btn btn-info margin-top-sm' %>
              <% end %>
              <%= link_to '分享', site, class: 'btn btn-info margin-top-sm' %>
              <%= link_to '留言', site_site_comments_path(site), class: 'btn btn-info margin-top-sm' %>
            </div>
          </div>
          <%= render partial: 'site_payment', locals: {site: site} %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<%= will_paginate @sites %>

app/views/sites/payment.html.erb
<ol class="breadcrumb">
  <li><a href="/">首页</a></li>
  <li><a href="/sites">后台</a></li>
  <li class="active">支付</li>
</ol>

<div class="row">
  <div class="col-md-10 col-md-offset-2 col-sm-12">
    <table class="table table-bordered table-striped">
      <tr><td>应用名称：</td><td><%= @site.title %> </td></tr>
      <tr><td>应用编号：</td><td><span class="label label-success"><%= @site.short_title %></span></td></tr>
      <tr><td>应用价格：</td><td><%= @site.site_payment.price %> </td></tr>
      <tr><td>支付状态：</td><td><%= payment_state(@site) %> </td></tr>
    </table>
  </div>
</div>

<% unless @site_payment.state == 'completed' %>
  <div class="row">
    <div class="col-sm-12 col-md-4">
      <!-- site info -->
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="bottom_bordered">方式一、支付宝支付</h3>
        </div>
        <% if mobile_device? %>
          <div class="panel-body">
            <%= image_tag('qr-alipay.png', alt: '维斗喜帖支付宝扫码支付', class: "img-responsive img-center") %>
            <br/>
            <h4>操作流程：</h4>
            <ol>
              <li>长按上面二维码，保存到手机</li>
              <li>请在手机上打开<mark>支付宝钱包</mark>，选择［扫一扫］，选择图片，选择保存的二维码</li>
              <li>支付成功后，发送您的应用编号<span class="label label-success"><%= @site.short_title %></span>到手机：<mark><%= ENV['CONTACT_MOBILE'] %></mark>，应用激活后会收到短信提示。</li>
              <li>没有安装支付宝钱包，可选择在电脑上支付</li>
            </ol>
          </div>
        <% else %>
          <div class="panel-body">
            <%= image_tag('qr-alipay.jpg', alt: '维斗喜帖支付宝扫码支付', class: "img-responsive img-center") %>
            <br/>
            <h4>操作说明：</h4>
            <ol>
              <li>请在手机上打开<mark>支付宝钱包</mark>，选择［扫一扫］,进入支付。</li>
              <li>支付成功后，发送您的应用编号<span class="label label-success"><%= @site.short_title %></span>到手机：<mark><%= ENV['CONTACT_MOBILE'] %></mark>，应用激活后会收到短信提示。</li>
            </ol>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-sm-12 col-md-4">
      <!-- site info -->
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="bottom_bordered">方式二、微信转账付款</h3>
        </div>
        <div class="panel-body">
          <p class="text-center">
            <%= image_tag('weixin-qrcode.png', alt: '维斗喜帖微信AA支付二维码', class: "img-responsive") %>
          </p>
          <h4>操作流程：</h4>
          <ol>
            <li>打开微信扫一扫上方二维码添加微信发红包进行支付</li>
            <li>支付成功后，2分钟后将收到应用激活码</li>
          </ol>          
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-md-4">
      <!-- site info -->
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="bottom_bordered">方式三、激活码支付</h3>
        </div>
        <div class="panel-body">
          <%= form_tag(site_verify_payment_token_path) do |f| %>
            <p>你的应用编号： <span class="label label-success"><%= @site.short_title %></span></p>
            <div class="input-group">
              <%=text_field_tag :code, nil, class: 'form-control', placeholder: "请输入6位数激活码" %>
              <div class="input-group-btn">
                <%= submit_tag '验 证', :class => 'btn btn-danger' %>
              </div>
            </div>
          <% end %>
          <br/>
          <h4>哪里可以获取激活码？</h4>
          <ul>
            <li>我们会给<mark>[商户版]会员</mark>发放激活码</li>
            <li>我们会给<mark>团购客户</mark>发放激活码</li>
            <li>我们会给<mark>个人定制用户</mark>发放激活码</li>
          </ul>
        </div>
      </div>
    </div>
    
  </div>
<% end %>

app/views/sites/send_sms.js.erb
alert("短信发送成功，接收可能有延迟，请注意查收；如果5分钟以后未收到，请检查一下垃圾短信箱。");
$("#send_sms_submbit").hide();

app/views/sites/themes.html.erb
<style type="text/css">
  .btn-radio {
    width: 100%;
  }
  .img-radio {
    opacity: 0.5;
    margin-bottom: 5px;
  }

  .space-20 {
      margin-top: 20px;
  }
</style>


  <div class="row">
    <div class="col-md-8">
      <%= form_tag site_set_theme_path, {class: 'form-horizontal'} do %>
        <%= hidden_field_tag 'theme_id', '' %>
        <div class="row">
           <h3 class="bottom_bordered">选择应用主题</h3>
          <% @themes.each do |theme| %>
            <div class="col-xs-4" style="margin: 5px 0px;">
              <button type="button" class="btn btn-default btn-radio" style="background-color: <%= theme.css_color %>;" data-preview="<%= get_demo_image_list(theme, 'preview_images', 'theme').first %>" data-theme="<%= theme.id %>"><%= theme.title %></button>
            </div>
          <% end %>
        </div>
        <div class="row space-20">
          <div class="col-xs-12">
            <div class="form-group">
              <div class="col-sm-6">
                <input type="submit" class="form-control btn btn-lg btn-block btn-meflat" value="保存所选">
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-4">
      <div class="iphone-bg">
        <img id="preview-image" src="http://placehold.it/225x400" class="img-responsive">
      </div>
    </div>
  </div>

<script type="text/javascript">
  //see: http://bootsnipp.com/snippets/featured/image-checkbox-buttons
  $(function () {
    $('.btn-radio').click(function(e) {
      $('.btn-radio').not(this).removeClass('active')
      $(this).addClass('active')

      $('#preview-image').attr("src", $(this).data("preview"));
      $('#theme_id').val($(this).data("theme"));
    });
  });
</script>